version: '2'
services:
  main:
    container_name: runner
    image: intelsdi/snap:alpine
    environment:
     - SNAP_VERSION=latest
    volumes:
      - ${PLUGIN_SRC}:/snap-plugin-collector-meminfo
    network_mode: "host"